(dcvc_env) work@main1[cAv1nfuw-session]:~/dcvc/DCVC$ python test_video.py \
    --i_frame_model_path ./checkpoints/cvpr2023_image_ssim.pth.tar \
    --p_frame_model_path ./checkpoints/cvpr2023_video_ssim.pth.tar \
 --rate_num 2 \
  --test_config ./DCVC-DC/dataset_config_example_yuv420.json \
  --cuda 0 \
  -w 1 \
  --write_stream 1 \
  --save_decoded_frame 1 \
  --force_zero_thres 0.12 \
  --output_path "$OUTJSON" \
  --force_intra_period -1 \
  --reset_interval 64 \
  --force_frame_num -1 \
  --check_existing 0 \
  --verbose 1
cannot import cuda implementation for inference, fallback to pytorch.
usage: test_video.py [-h] [--force_zero_thres FORCE_ZERO_THRES] [--model_path_i MODEL_PATH_I] [--model_path_p MODEL_PATH_P] [--rate_num RATE_NUM]
                     [--qp_i QP_I [QP_I ...]] [--qp_p QP_P [QP_P ...]] [--force_intra FORCE_INTRA] [--force_frame_num FORCE_FRAME_NUM]
                     [--force_intra_period FORCE_INTRA_PERIOD] [--reset_interval RESET_INTERVAL] --test_config TEST_CONFIG [--force_root_path FORCE_ROOT_PATH]
                     [--worker WORKER] [--cuda CUDA] [--cuda_idx CUDA_IDX [CUDA_IDX ...]] [--calc_ssim CALC_SSIM] [--write_stream WRITE_STREAM]
                     [--check_existing CHECK_EXISTING] [--stream_path STREAM_PATH] [--save_decoded_frame SAVE_DECODED_FRAME] --output_path OUTPUT_PATH
                     [--verbose_json VERBOSE_JSON] [--verbose VERBOSE]
test_video.py: error: unrecognized arguments: --i_frame_model_path ./checkpoints/cvpr2023_image_ssim.pth.tar --p_frame_model_path ./checkpoints/cvpr2023_video_ssim.pth.tar
